name: gwong_mfb
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.5.1
  gap: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  lottie: ^1.1.0
  number_display:
  shimmer: ^2.0.0
  provider: ^6.0.2
  local_auth: ^2.1.0
  google_fonts: ^3.0.1
  timer_button: ^2.0.0
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.3+3
  dropdown_search: ^5.0.2
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  percent_indicator: ^3.4.0
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.9.0
  intl_phone_number_input: ^0.7.0+2
  flutter_sequence_animation: ^4.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  
  

flutter_icons:
  image_path: "assets/logo/logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/pattern/
    - assets/icons/img/
    - assets/icons/icons/
    
  fonts:
    - family: Inter-Black
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          # style: normal
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter-ExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
    - family: Inter-ExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf